spring:
  datasource:
    url: jdbc:mysql://172.24.65.14:3306/ShortVideo?serverTimeZone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
