spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1

  datasource:
    url: jdbc:mysql://192.168.236.128:3306/ShortVideo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  tomcat:
    max-http-form-post-size: -1